version = "2.0.0.2"

[global]
author = "jgrelet IRD March 2021"
debug = true
echo = true
screenWidth = 800
screenHeight = 600

[tools]
name = "tools/Angulate.xls"

[config]
reference = "surface"
bottomDepth = 0
library = "library/example.xls"
